name: Windows
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    if: github.repository == 'kcdodd/partis-pyproj'
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: |
          3.8
          3.9
          3.10
          3.11
          3.12
          3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r pkgaux/test_requirements.txt
    - name: Test with pytest
      run: |
        nox -s prepare test report
